# Generated by Django 5.1.4 on 2025-01-22 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Equipe')),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Título do Projeto')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
                ('dt_inicio', models.PositiveBigIntegerField(verbose_name='Data de Início')),
                ('dt_final', models.PositiveBigIntegerField(verbose_name='Data de Término')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-dt_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Membro')),
                ('funcao', models.CharField(max_length=50, verbose_name='Função na Equipe')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='membros', to='app_projeto.equipe')),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
                'ordering': ['equipe__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Atividade')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
                ('dt_limite', models.PositiveBigIntegerField(verbose_name='Data Limite')),
                ('feito', models.BooleanField(default=False)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='atividades', to='app_projeto.projeto')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'ordering': ['-dt_limite', 'nome'],
            },
        ),
    ]
