# Generated by Django 5.1.4 on 2025-01-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='dt_final',
            field=models.DateField(verbose_name='Data de Término'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='dt_inicio',
            field=models.DateField(verbose_name='Data de Início'),
        ),
    ]
