# Generated by Django 5.1.4 on 2025-01-22 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto', '0002_alter_projeto_dt_final_alter_projeto_dt_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='ativa',
            field=models.BooleanField(default=True, verbose_name='Em atividade'),
        ),
        migrations.AddField(
            model_name='membro',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='membro',
            name='telefone',
            field=models.CharField(default='(99) 99999-9999', help_text='(99) 99999-9999', max_length=15, verbose_name='Teçefone'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='app_projeto.equipe'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='orcamento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Orçamento'),
        ),
    ]
